name: Generate Contribution Snake

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC

jobs:
  snake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate contribution snake
        uses: Platane/snk@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user: nirajang20
          output: dist/github-contribution-grid-snake.svg
          dark_output: dist/github-contribution-grid-snake-dark.svg

      - name: Push to output branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: output
          directory: dist
          github_token: ${{ secrets.GITHUB_TOKEN }}
